import test from 'node:test';
import assert from 'node:assert/strict';
import { createCheckpoint, mark, markConverged, validateDesired, importListingMarkdown, PHASES, EXIT, EvidenceStore } from '../src/index.mjs';
import fs from 'node:fs';
import path from 'node:path';

test('checkpoint refuses evidence-free convergence', () => { const cp = createCheckpoint({ productId: 'P' }); assert.throws(() => markConverged(cp, 'listing', {}), /evidence/); });
test('checkpoint requires full evidence chain', () => { const cp = createCheckpoint({ productId: 'P' }); mark(cp, 'listing', 'Observed'); mark(cp, 'listing', 'NeedsChanges', { diff: [{ field: 'x' }] }); mark(cp, 'listing', 'Applying'); mark(cp, 'listing', 'AppliedUnverified'); markConverged(cp, 'listing', { pageKind: 'SubmissionOverview', coldDiff: [], overviewStatus: 'Complete', overviewUrl: 'https://example.test', evidenceIds: ['listing.json'] }); assert.equal(cp.phaseStatuses.listing, 'Converged'); assert.deepEqual(cp.convergedPhases, ['listing']); });
test('all phases and exit codes are explicit', () => { assert.deepEqual(PHASES, ['availability', 'properties', 'age-ratings', 'packages', 'listing', 'options']); assert.equal(EXIT.DIFF, 4); });
test('listing import handles mixed Chinese and English headings', () => { const root = path.resolve('.cache', `listing-test-${process.pid}`); fs.mkdirSync(root, { recursive: true }); const file = path.join(root, 'listing.md'); fs.writeFileSync(file, '## 简短摘要（Short Description）\n短文\n## Description\n长文\n## App Features\n- A\n- B\n## Search Terms\na;b'); const desired = { values: {} }; importListingMarkdown(desired, file); assert.equal(desired.values.shortDescription, '短文'); assert.equal(desired.values.description, '长文'); assert.deepEqual(desired.values.features, ['A', 'B']); assert.deepEqual(desired.values.keywords, ['a', 'b']); });
test('strict desired validation catches missing age answers and assets', () => { const errors = validateDesired({ productName: 'P', values: { description: 'd', shortDescription: 's', features: ['f'], keywords: ['k'] }, listing: { screenshot: true }, assets: {}, ageRatings: { answers: {} } }, { strict: true }); assert.ok(errors.some(error => error.includes('ageRatings.answers'))); assert.ok(errors.some(error => error.includes('assets.screenshot'))); });
test('evidence store keeps binary screenshots binary', () => { const root = path.resolve('.cache', `evidence-test-${process.pid}-${Date.now()}`); const store = new EvidenceStore(root, root); const file = store.write('shot.png', Buffer.from([0x89, 0x50, 0x4e, 0x47])); assert.deepEqual([...fs.readFileSync(path.join(root, 'evidence', 'shot.png'))], [0x89, 0x50, 0x4e, 0x47]); assert.match(file, /shot\.png$/); });
