import path from 'node:path';
import fs from 'node:fs';
import { writeAtomic } from '@quick-app/core';
import { waitForPageKind, waitUntil } from './inspector.mjs';

export async function reserveProduct({ page, appRoot, desired, name, logger }) {
  const parsed = new URL(desired.site.baseUrl); const locale = parsed.pathname.split('/').filter(Boolean)[0] || 'zh-cn'; const url = `${parsed.origin}/${locale}/dashboard/apps-and-games/overview`; logger?.info('reserve-start', { url, name }); await page.goto(url, { waitUntil: 'domcontentloaded', timeout: 45_000 }); await waitForPageKind(page, ['ProductOverview', 'SubmissionOverview'], { operation: 'apps and games overview' });
  const newProduct = page.getByRole('button', { name: /新产品|New product/i }).first(); if (!(await newProduct.count())) throw Object.assign(new Error('new product button not found'), { code: 'SCHEMA_DRIFT' }); await newProduct.click(); const msix = page.getByText(/MSIX|PWA/i).first(); if (await msix.count()) await msix.click();
  const nameInput = page.getByRole('textbox', { name: /名称|name|产品/i }).first(); if (!(await nameInput.count())) throw Object.assign(new Error('product name field not found'), { code: 'SCHEMA_DRIFT' }); await nameInput.fill(name); const check = page.getByRole('button', { name: /检查可用性|Check availability/i }).first(); if (await check.count()) await check.click(); await waitUntil(async () => /可用|available/i.test((await page.locator('body').innerText()).slice(-2000)), { timeoutMs: 30_000, label: 'product name available' }); const reserve = page.getByRole('button', { name: /保留产品名称|Reserve product name/i }).first(); if (!(await reserve.count())) throw Object.assign(new Error('reserve product name button not found'), { code: 'SCHEMA_DRIFT' }); await reserve.click();
  await waitUntil(async () => /\/products\/[^/]+|ProductId|产品标识/i.test(page.url() + (await page.locator('body').innerText()).slice(0, 4000)), { timeoutMs: 60_000, label: 'product created' }); const productId = page.url().match(/\/products\/([^/?#]+)/i)?.[1] ?? page.url().match(/[?&](?:productId|id)=([^&#]+)/i)?.[1]; if (!productId) throw new Error(`product was reserved but ProductId was not found in ${page.url()}`);
  const identity = await scrapeIdentity(page, desired, appRoot); if (!identity.identityName || !identity.publisher || !identity.publisherDisplayName) throw Object.assign(new Error('Product Identity fields were not fully observed after reservation'), { code: 'SCHEMA_DRIFT', identity }); desired.productId = productId; desired.productName = name; desired.package.identityName = identity.identityName; desired.package.publisher = identity.publisher; desired.package.publisherDisplayName = identity.publisherDisplayName; const stored = structuredClone(desired); for (const key of ['path', 'manifestPath']) if (stored.package?.[key]) stored.package[key] = path.relative(appRoot, stored.package[key]).replaceAll('\\', '/'); if (stored.assets?.screenshot) stored.assets.screenshot = path.relative(appRoot, stored.assets.screenshot).replaceAll('\\', '/'); for (const item of Object.values(stored.listing?.assets ?? {})) if (item.path) item.path = path.relative(appRoot, item.path).replaceAll('\\', '/'); if (stored.listingMarkdown) stored.listingMarkdown = path.relative(appRoot, stored.listingMarkdown).replaceAll('\\', '/'); writeAtomic(appRoot, path.join(appRoot, 'store', 'desired-state.json'), stored); if (identity.manifestPath) updateManifest(identity.manifestPath, { ...identity, displayName: name }); logger?.pass('product reserved', { productId, identity }); return { productId, identity };
}

async function scrapeIdentity(page, desired, appRoot) {
  await waitUntil(async () => /Identity\.Name|Package\/Identity\/Name|PublisherDisplayName/i.test(await page.locator('body').innerText()), { timeoutMs: 30_000, label: 'package identity table' });
  const text = await page.locator('body').innerText(); const value = label => { const regex = new RegExp(`${label}[^\\n]*\\n?\\s*([^\\n]+)`, 'i'); return text.match(regex)?.[1]?.trim() ?? ''; }; return { identityName: value('Identity.Name|Package/Identity/Name'), publisher: value('Publisher(?!Display)'), publisherDisplayName: value('PublisherDisplayName'), manifestPath: desired.package.manifestPath ? path.resolve(appRoot, desired.package.manifestPath) : '' };
}
function updateManifest(filePath, values) { if (!filePath || !fs.existsSync(filePath)) return; let xml = fs.readFileSync(filePath, 'utf8'); xml = xml.replace(/(<Identity\b[^>]*\bName\s*=\s*["'])[^"']*/i, `$1${escapeXml(values.identityName || 'PENDING.IDENTITY')}`).replace(/(<Identity\b[^>]*\bPublisher\s*=\s*["'])[^"']*/i, `$1${escapeXml(values.publisher || 'CN=PENDING')}`).replace(/(<DisplayName>)[^<]*/i, `$1${escapeXml(values.displayName)}`).replace(/(<PublisherDisplayName>)[^<]*/i, `$1${escapeXml(values.publisherDisplayName || 'Quick App Maker')}`).replace(/(VisualElements\b[^>]*\bDisplayName\s*=\s*["'])[^"']*/i, `$1${escapeXml(values.displayName)}`); fs.writeFileSync(filePath, xml, 'utf8'); }
function escapeXml(value) { return String(value ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&apos;' }[c])); }
